steps:
  - name: node
    entrypoint: npm
    args:
      - install
  - name: node
    entrypoint: npm
    args:
      - install
      - run
      - start
  # - name: 'gcr.io/kaniko-project/executor:latest'
  #   args:
  #     - '--destination=gcr.io/$PROJECT_ID/sfs-chatbot-dev:$COMMIT_SHA'
  #     - '--cache=true'
  #     - '--cache-ttl=48h'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - sfs-chatbot-dev
      - '--image'
      - 'gcr.io/$PROJECT_ID/sfs-chatbot-dev:$COMMIT_SHA'
      - '--region'
      - us-central1
      - '--allow-unauthenticated'
